### ISSUE TITLE
Toolbar icons are unreadable

### ISSUE THREAD

**Issue by StanGets** [checkmyhttps/checkmyhttps#10]
CheckMyHTTPS 5.2.0 / Firefox 65.0 (x64) / Windows 7 (x64)

Hi,

First, the good comment : CheckMyHTTPS 5.2.0 which supports the WebExtension TLS API (the Python script is now optional on Firefox > 62) works perfectly. Nice to find it back (I avoided the python era due to Webextension format).

Now, the less good. Only a cosmetic issue but with the incidence on toolbar buttons/icons readability: when it comes to 16px icons the design has to fill the 196 pixels. Checkmyhhtps icons, displayed as 16px, end up with a 12px width and 40% of the height to draw the top of the padlock. Colors with no contrast, the result seems closer to a stain than to a well designed icon.

To give an example, this image with Checkmyhttps icons on top, and an example of readable icons under:

![untitled 1](https://user-images.githubusercontent.com/42912760/52083402-9d43ba00-259f-11e9-9c97-576bbfc5f284.jpg)

See the difference?

Improving your toolbar icons would be a substantial contribution to readability of a great extension.

Thanks (et merci!)

**Comment by catarinadf** [comment]
Hello,

Thank you for your feedback.
We took it into consideration and came up with new icons. 
We were thinking that we could keep the original lock, the grey one, but then when someone would click on it, they would get one of the following images:

![cmh_github_new_images](https://user-images.githubusercontent.com/41592444/53013219-7dd4da00-3445-11e9-95f7-1be4e165425c.png)

What do you think ?

**Comment by StanGets** [comment]
Hello @catarinadf and thanks for considering an issue which is only cosmetic hence not really an issue. Moreover cosmetic features tend to be essentially subjective even if I believe there is some substantial objectivity in my approach.

I think the new icons you display above are far better provided they fill 100% of their area.
Also, a white check-mark on a light-green background will hardly be visible in 16px : why not a black check-mark on a yellow `#FFFF00` background?
Same for the red question-mark on black : why not white on black?

The point is always what renders on 196 square pixels...

And I'm not even elaborating on the browser's theme, be it lite or dark: some developers even propose 2 sets of icons for this purpose. To have a universal icon visibility I think 3 conditions need to be filled:.

1- If icon background is lite, give it a dark border;
2- if icon background is dark, give it a lite border;
3- Basic design (Mona Lisa doesn't fit on 196 pixels!) and good contrast between design and background.

That's all! I'm certainly calling hilarity among some of us but when you have a small screen with small icons and moreover many of them, being able to spot immediately your toolbar icon is a relief, especially for dynamic icons (those which reflect a modification of what they handle).

Again let us smile! But, after all, if an aircraft's cockpit or a nuclear plant's operation center had buttons as some icons I happen to discover throughout the dozens I test... planes would crash and power would fail more often :=)

Thanks to you!

**Comment by StanGets** [comment]
I forgot to mention this:

An extension's toolbar button icon can easily be replaced, at least in Firefox, with a dedicated line in the user's profile / chrome / userChrome.css file, with something like, i.e.
```

/* HTTPS Everywhere */
#https-everywhere_eff_org-browser-action .toolbarbutton-icon {
list-style-image: url(UserData/HTTPSEVERYWHERE-active.png)!important;}

But if the icon is dynamic then it may ba as well replaced given the toolbar button provides a tooltiptext specific to the extension's status, such as:

```
#https-everywhere_eff_org-browser-action[tooltiptext="HTTPS Everywhere (blocking)"] .toolbarbutton-icon {
list-style-image: url(UserData/HTTPSEVERYWHERE-blocking.png)!important;}
```

#https-everywhere_eff_org-browser-action[tooltiptext="HTTPS Everywhere (disabled)"] .toolbarbutton-icon {
opacity:0.40 !important;}

**Comment by StanGets** [comment]
Why is it such a problem to have these icons modified? Pure cosmetic, takes a minute to change them...

I see practically nothing when the check is validated:

![Sans titre 1](https://user-images.githubusercontent.com/42912760/54070556-8d378e00-4261-11e9-90fd-a0e58afaa847.jpg)

What's the point of an extension if its icon is so hard to spot? It takes only a minute for the developer to change it!

**Comment by catarinadf** [comment]
Hello,

We would like to apologize for the delay. The icons will be changed as soon as possible.
However, it will depend on our availabilities as we currently have four projects under development: a Firefox add-on, a Chrome add-on, an Android app (coming soon) and an iOS app (coming soon).

Best regards.

**Comment by StanGets** [comment]
@catarinadf I read you loud and clear. I wasn't aware of the multi-platform development which explains it all.

Thanks again for this unique extension, much appreciated, the only in its category.
