### ISSUE TITLE
Chosen Server Revert to Default After Each Restart

### ISSUE THREAD

**Issue by Kraxys** [checkmyhttps/checkmyhttps#11]
I  currently use CheckMyHttps 5.2.1. In "Settings" I have switched from checkmyhttps.net to an other server, have changed the sha1 and sha256 fingerprint, and have clicked on "save". All is working well during the session, but after closing and restarting my browser, the server this addon use reverted to checkmyhttps.net.

Tested on FF 65 with no other addon, on W7.

PS: My browser's privacy setting is "never remember history".

**Comment by Tom-H-** [comment]
Hello,

We cannot reproduce your problem.
I have tried to install Firefox 65.0.1 on Windows 7, install CheckMyHTTPS 5.2.1, set my check server and restart Firefox. But my settings have not been reset to the default value.

Can you try to change a checkbox setting and see if it is persistent?
Also, can you try with another Firefox extension? (maybe this [Firefox support page](https://support.mozilla.org/kb/how-to-fix-preferences-wont-save) can help you...)
If you add a bookmark, is it kept after a restart?

If only the check server setting is reset, can you send us the URL of your check server?

**Comment by Tom-H-** [comment]
Hello,

Any news?
Have you solved your problem?
