### ISSUE TITLE
Server Reverting to Default After Each Restart

### ISSUE THREAD

**Issue by Kraxys** [checkmyhttps/checkmyhttps#12]
I continue what I said in #11, because the problem continues to happen on every browser I use, on every PC I use.

I just checked that again this time on a fresh FF 66.0.4 portable, without any customization  without any other addon:

I Installed CheckMyHttps from AMO, checked "_Check page on load_" and "_alert on Unicode IDN_", and replaced the test server _https://checkmyhttps.net_ by _https://www.google.com_, (but I can choose _https://example.com_ as well) then clicked on "get fingerprint", then clicked on "save".

Here is what I get just before closing the browser:
https://postimg.cc/0MNtLsxz

Then I restarted the browser, and here what I get: The test server reverted to _https://checkmyhttps.net_:
https://postimg.cc/RNx7tB8w

And for giving you an answer to your reply in #11:  when, for testing purpose, I uncheck "_Check page on load_"and "_alert on Unicode IDN_", then close and restart my browser, these preferences remain unchecked, so unchecking them is persistent.

And when I install eg uBlock, the preferences I check in its UI are persistent too, I never have had a problem with that.

I hope it helps...
 
It's a pity the server always reverts to default, because the feature provided by this addon is really nice

Currently using CheckMyHttps 5.3.0 on FF 66.0.4, W7

**Comment by Tom-H-** [comment]
Hello,

Your check server seems to be invalid. When you click on the `save` button, the WebExtension checks that the new check server is correct before save it.
So you need to have the green text "Settings saved" appear. Then the extension reloads itself (so you do not need to restart Firefox).

When you have set up your own [check server](https://github.com/checkmyhttps/checkmyhttps/tree/master/server-php), set the full URL without "api.php" at the end. You can check that it is working by checking `https://kraxys.me/api.php?host=checkmyhttps.net&port=443`.

**Comment by Kraxys** [comment]
> 
> 
> Hello,
> 
> Your check server seems to be invalid. When you click on the `save` button, the WebExtension checks that the new check server is correct before save it.
> So you need to have the green text "Settings saved" appear. Then the extension reloads itself (so you do not need to restart Firefox).
> 
> When you have set up your own [check server](https://github.com/checkmyhttps/checkmyhttps/tree/master/server-php), set the full URL without "api.php" at the end. You can check that it is working by checking `https://kraxys.me/api.php?host=checkmyhttps.net&port=443`.

Okay! Thanks for the explanation.
