### ISSUE TITLE
Option to disable the notification

### ISSUE THREAD

**Issue by koterpillar** [checkmyhttps/checkmyhttps#13]
I'd like to leave the icon in the status bar on, but not see the pop-up notification.

**Comment by catarinadf** [comment]
Hello koterpillar, thank you for your feedback.
Would it be ok if we add a checkbox on the settings of the add-on so the user can choose to disable the notifications?

**Comment by koterpillar** [comment]
Yes, that would be perfect.

**Comment by catarinadf** [comment]
Hello koterpilar, the new version of CheckMyHTTPS has an option to disable the notifications.That option is set to false by default in the add-on's settings.
