### ISSUE TITLE
Self-hosted server check broken due to outdated fingerprint

### ISSUE THREAD

**Issue by n0rc** [checkmyhttps/checkmyhttps#14]
If I try to use my own server API and try to verify my server fingerprint, this verification always fails because of a hard-coded but outdated fingerprint:
https://github.com/checkmyhttps/checkmyhttps/blob/53158d6f0ddc23ee9e516a7567e16151bd0465f6/webextension/add-on/lib/options.js#L28

The check is done here:
https://github.com/checkmyhttps/checkmyhttps/blob/53158d6f0ddc23ee9e516a7567e16151bd0465f6/webextension/add-on/lib/api.js#L66

**Comment by rexy74** [comment]
I apologize for this behaviour. We've performed tests with the new certificate. I've just reinstalled the old one which is enabled until next 1st December. We're searching for a solution in order not to have to update the extension each time we change the certificate....
Any idea ?

**Comment by n0rc** [comment]
@rexy74 If you hard-code a certificate fingerprint there is no way around updating the addon when the certificate (fingerprint) changes.

In my opinion it is enough if you just check against the API server fingerprint that the user provides. There is no need to also check whether the user's API server works correctly, because the user is 100% responsible for that.

**Comment by rexy74** [comment]
We have just updated the addon and certificate simultaneously. We will look for a more sustainable solution.
