### ISSUE TITLE
Checkmyhttps doesn't alert when its certificate SHA256 fingerprint is wrong

### ISSUE THREAD

**Issue by InfoLibre** [checkmyhttps/checkmyhttps#15]
I always had alerts for all https websites. I thought it was a MITM of my provider but no. It was simply the SHA256 fingerprint of https://checkmyhttps.net that was wrong in the extension parameters :
Could you add a popup message in the extension when it occurs ?

![image](https://user-images.githubusercontent.com/3955499/73530119-2d694900-4418-11ea-9c13-ce3ec6123dd2.png)

**Comment by checkmyhttps** [comment]
You're right, we don't have a special notification when the fingerprints differ. It's a good idea. We've updated CMH when we have changed our server certificate (V 5.4.1). Normally you only have to update when it occurs. Nevertheless, we are searching for a solution in order not to have to do that each time we change the server certificate.

**Comment by InfoLibre** [comment]
Perhaps Checkmyhttps could verify its fingerprint each time we start the browser and show an alert if it's wrong.

**Comment by InfoLibre** [comment]
Or you could publish a new version each time the fingerprint changes. So, the extension will be automatically updated with the new fingerprint.
