### ISSUE TITLE
Suggestion : adding tooltip text

### ISSUE THREAD

**Issue by Cade66** [checkmyhttps/checkmyhttps#17]
Hi,
Running flawlessly CheckMyHTTPS 5.5, most appreciated.
I'm suggesting what appears as superfluous for most users yet has been asked to me by someone starting in the computer area:
Adding the tooltip text to CheckMyHTTPS browser-action toolbar button's status, as described at [CheckMyHttps' homepage](https://checkmyhttps.net/),

![1](https://user-images.githubusercontent.com/65161029/82729012-680f2e00-9cf4-11ea-9785-c02f678fcbce.jpg)

Just to come in handy to some who don't (yet) fully, intuitively master icons' symbols :=)

Thanks!

**Comment by QuentinClrt** [comment]
Hello Cade66,
This improvement will be available on the next CMH version. (which is coming soon)
Thank you and stay tuned !

**Comment by Cade66** [comment]
Thanks for the info @QuentinClrt

**Comment by rexy74** [comment]
The 5.5.1 version has just been published with your suggestion. Thx

**Comment by Cade66** [comment]
Updated CheckMyHTTPS to ver. 5.5.1 -- I already mentioned _most appreciated_ for previous 5.5.0 so I'll innovate: _**most appreciated+1**_
Thanks :=)
