### ISSUE TITLE
This website has several server certificates. We could not guarantee security of your HTTPS connection.

### ISSUE THREAD

**Issue by kopach** [checkmyhttps/checkmyhttps#23]
Hi. I'm using Firefox extension and I'm getting following alert message "This website has several server certificates. We could not guarantee security of your HTTPS connection." on pages like https://www.youtube.com/ or https://photos.google.com/

Could you, please, help to understand what those message mean and how to fix this? Also, is there any chance to disable such alerts and only show status as extension icon?  I've enabled option "Check when the page loads" and now get alert every time I open youtube or google photos.
Thanks

**Comment by QuentinClrt** [comment]
Hello kopach,

This type of "error" permits us to alert our users that the current site owns several certificates. Google's web sites owns several certificates. As an example, you can compare those we get using the "Manual check" on our site [checkmyhttps.net](url) versus the Youtube ones you get to see the fingerprints conflict.

Please, if you want not to be alerted by this type of notification, check the "Disable notifications" option into the settings extension. Priority notifications (such as a "Default server unreachable") will not be disabled in this case.

CheckMyHTTPS team.

**Comment by kopach** [comment]
Hi @QuentinClrt , thanks for your explanation. "Disable notifications" option works perfect for me, thanks. 
Could you also please help to understand severity of such type of "error" and why this should be presented to user as alert? Does this mean I have security issue? Am I'm spied?

**Comment by QuentinClrt** [comment]
Hello @kopach,

Once this return printed on your screen, you can not be sure about the servers fingerprints because they are using a specific technology (CDN). Then, you do not have any issue and you are not spied if you have this notification, but, you can not be sure about the fingerprints because we can not verify those technologies.

Whitelisted servers that can not be verified are listed into the whitelist's API webserver : https://github.com/checkmyhttps/checkmyhttps/blob/master/server-php/www/api_whitelist.php

CheckMyHTTPS Team.

**Comment by kopach** [comment]
Hello @QuentinClrt. Thanks for your explanation. For some reason I don't see this alert anymore on those pages so issue is solved for now. But still I would like to understand the reason of this alert (notification). Does this alert mean I potentially could have been spied on? If there is no such a chance (even potentially) – then I don't see the reason to have those alerts enabled by default or even shown at all. On the other hand, if there is such a chance – then it makes sense to me. Could you elaborate on this a bit more, pelase? Thanks in advance for your time.
