### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [checkmyhttps/checkmyhttps#25]
It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://help.github.com/en/enterprise/2.13/user/articles/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by Neustradamus** [comment]
@checkmyhttps: It is not done, can you reopen this ticket?

**Comment by checkmyhttps** [comment]
@Neustradamus : what is the benefit to do that ?

**Comment by Neustradamus** [comment]
@checkmyhttps: I think that the best solution is (in few minutes):
- Change your username to checkmyhttpsaccount (or other): https://github.com/settings/admin
- Create checkmyhttps organization: https://github.com/organizations/new

And:
- Transfer checkmyhttps into checkmyhttps org: https://github.com/NEWACCOUNTUSERNAME/checkmyhttps/settings

No lost, you can see, for examples:
- https://github.com/nerzhul/ocsms
- https://github.com/tigaseinc/tigase-server

Some links:
- https://help.github.com/en/github/getting-started-with-github/types-of-github-accounts
- https://github.community/t/best-practices-for-organizations/10205
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams
