### ISSUE TITLE
Is site down?

### ISSUE THREAD

**Issue by kopach** [checkmyhttps/checkmyhttps#26]
Hi. It looks like https://checkmyhttps.net/ server is down. I've verified it also on following resources (so, seems like it's not only for me)

- https://www.isitdownrightnow.com/
- https://isitdown.me/

---
<img width="546" alt="image" src="https://user-images.githubusercontent.com/8749624/100287539-1c746000-2f75-11eb-9a30-0c53954102f1.png">

<img width="537" alt="image" src="https://user-images.githubusercontent.com/8749624/100287572-28602200-2f75-11eb-89f3-3e2d0e1d18db.png">
---

Is this planned maintenance or some issue? Any news when it will be up again? Thanks.

**Comment by checkmyhttps** [comment]
Hi,

You are right. It's a general problem in a data center. CMH will be back in a few hours (we sleep in France now 😉).

Best regards,

Richard REY (Rexy) [cid:112ed9c3-b7b0-4469-9d1c-4d51168c2e48] <https://www.linkedin.com/in/rexy74/>
________________________________
Enseignant et ingénieur de recherche en Cybersécurité
Laboratoire CNS (Confiance Numérique et Sécurité)
ESIEA - École d'ingénieurs d'un numérique utile
53000 LAVAL - Tel : +33 (0)243594603
ALCASAR<http://www.alcasar.net/> & CheckMyHTTPS<https://checkmyhttps.net/> projects leader
________________________________
De : Ihor <notifications@github.com>
Envoyé : mercredi 25 novembre 2020 23h24
À : checkmyhttps/checkmyhttps <checkmyhttps@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [checkmyhttps/checkmyhttps] Is site down? (#26)


Hi. It looks like https://checkmyhttps.net/ server is down. I've verified it also on following resources (so, seems like it's not only for me)

  *   https://www.isitdownrightnow.com/
  *   https://isitdown.me/

________________________________

[image]<https://user-images.githubusercontent.com/8749624/100287539-1c746000-2f75-11eb-9a30-0c53954102f1.png>

[image]<https://user-images.githubusercontent.com/8749624/100287572-28602200-2f75-11eb-89f3-3e2d0e1d18db.png>

---

Is this planned maintenance or some issue? Any news when it will be up again? Thanks.

**Comment by kopach** [comment]
seems back to normal again. thanks
