### ISSUE TITLE
Compatibility with Microsoft Edge Chromium

### ISSUE THREAD

**Issue by srlennon** [checkmyhttps/checkmyhttps#28]
Extension from Goggle Web Store installs fine but when attempt to check a site it just sits there with the black and white question mark box. Would be nice if this also worked in Edge Chromium browser.

**Comment by checkmyhttps** [comment]
The new 5.5.4 version works on "FF" + "Chrome" + "Edge"

**Comment by checkmyhttps** [comment]
The new 5.5.4 version works on "FF" + "Chrome" + "Edge"
