### ISSUE TITLE
Extension server certificate SHA256 does not match https://checkmyhttps.net

### ISSUE THREAD

**Issue by philcolbourn** [checkmyhttps/checkmyhttps#30]
Just installed extension v5.5 from https://chrome.google.com/webstore/detail/checkmyhttps/jbnodnfpdcegpnflleanllmiihkinkio

server certificate is in extension is different to one in [options.html](https://github.com/checkmyhttps/checkmyhttps/blob/master/webextension/options/options.html)

For https://checkmyhttps.net/ I get
8B944DBC442DA0892C307DEF6C971B671267BF033E8479C567E173973F970B9F

for options.html I get
8B944DBC442DA0892C307DEF6C971B671267BF033E8479C567E173973F970B9F

But installed extension has thishttps://checkmyhttps.net/
C8F129A6D02194583A6B205B27AB7A246651A9915857E8DB24C1909D6F54F324

**Comment by checkmyhttps** [comment]
Due to a time shift between the CMH new version & the website certificate.
