### ISSUE TITLE
Addon doesnt seem to work for my companys ssl decryption

### ISSUE THREAD

**Issue by strunker** [checkmyhttps/checkmyhttps#34]
Hello,

my org recently started https ssl decryption. I wanted to find a way to alert myself on any site where they are doing this on, so I would be aware and not login to the site.

Your addon I believe is supposed to alert on any site that is using a non public cert. you can see below the ssl decryption on dropbox.com. 
![image](https://user-images.githubusercontent.com/6154660/118893383-56913f80-b8d0-11eb-8234-7a7f24da7dc1.png)

When off vpn, and the site isnt decrypted by my org is seen below. Any advice on this? The root cert for my companies domain is trusted because it gets delivered to my machine from the domain bind. I could always remove it every day, but any time i login the domain will just place it back again. The ssl decryption leverages the internal cert to do the decryption and middle man the traffic. 

Hope this make sense, and reading the "how" of how the addon works I would think that my companies internal private root cert, even though it is trusted, wouldnt fool the addon. I tested this across several sites that they are decrypting, none of them were picked up by the addon. 

![image](https://user-images.githubusercontent.com/6154660/118893439-6c066980-b8d0-11eb-956c-0c87648392a8.png)

**Comment by strunker** [comment]
Just a quick note works fine in firefox. This is chrome specific
![image](https://user-images.githubusercontent.com/6154660/118895680-9ce89d80-b8d4-11eb-84b1-309f19d01b32.png)

**Comment by strunker** [comment]
![image](https://user-images.githubusercontent.com/6154660/118896795-0d90b980-b8d7-11eb-8516-28ab84e73531.png)

seems completely broken in chrome. after seeing how it supposed to work in firefox, it doesnt seem to work period in chrome, the icon never updates, the check never returns a result like it does on firefox.

**Comment by rexy74** [comment]
Hello Strunker,
You are right, the chrome version of CMH need an update. We have focused on Firefox.
Right now, some works are done for Android & Ios Apps in order to be able to check Internet access without web browser.

**Comment by checkmyhttps** [comment]
The new 5.5.4 version works on FF + Edge + Chrome
