### ISSUE TITLE
Cadenas Bleu

### ISSUE THREAD

**Issue by JustusDE** [checkmyhttps/checkmyhttps#4]
Salut les amis, j'ai un cadenas bleu sur Youtube et Gmail est-ce normal ?

**Comment by Tom-H-** [comment]
Bonjour,

Le cadenas bleu signifie que CheckMyHTTPS ne peut pas garantir que votre connexion est sécurisée. Nous whitelistons certains noms de domaine utilisant plusieurs certificats (tel que ceux de Google).

Afin de vérifier que vous communiquez bien au bon serveur, CheckMyHTTPS compare le certificat de l'utilisateur avec celui obtenu par son serveur. Les sites utilisant plusieurs certificats génèrent donc des faux positifs. Lorsque les certificats sont différents, nous avons remplacé l'alerte par un message d'avertissement.
