### ISSUE TITLE
Extension and manual checks do not resolve

### ISSUE THREAD

**Issue by Cade66** [checkmyhttps/checkmyhttps#52]
Hi,

_CheckMyHTTPS_ 5.70 on _Firefox_ 105.0+ does not resolve checking.
Same with [Manual check ](https://checkmyhttps.net/check.php?language=en) which displays after a few seconds _The domain name is unknown_

Could be me, but I don't see where, how.
Anyone else experiencing the same issue?

**Comment by Shiluba** [comment]
Hi @Cade66,

We are indeed currently experiencing issues with DNS resolutions on our server.
We will try to fix it soon but you don't have to worry, this issue is not specifically related to CheckMyHTTPS.

Thanks for interest in the project.

Sylvain
