### ISSUE TITLE
Always red on chromium+python

### ISSUE THREAD

**Issue by xxxmf** [checkmyhttps/checkmyhttps#69]
The check is always red on chromium, manual check look ok so it should be green. Everything green on firefox, just on chromium everything red.

**Comment by Shiluba** [comment]
Hello @xxxmf,
Thank you for your message.

We just updated our Chromium extension (5.6.0 -> 5.6.1).

Actually, as the HTTPS certificate of our server has been recently updated, our Chromium extensions were not able to recognize the server's fingerprint anymore.
Our Firefox extension still works as it implements a signature verification, and does not rely anymore on SSL Pinning.
We are currently working on implementing this signature verification system on the Chromium extensions and on the mobile app.

You can now find the latest version of CheckMyHTTPS for Google Chrome on this Github repository, on [our website](https://checkmyhttps.net/) and on the official [Chrome Web Store](https://chrome.google.com/webstore/detail/checkmyhttps/jbnodnfpdcegpnflleanllmiihkinkio).

Regards,

CheckMyHTTPS Team
