### ISSUE TITLE
webextention on private server seem to not work.

### ISSUE THREAD

**Issue by llevet** [checkmyhttps/checkmyhttps#71]
Hi,
Just installed my own server folowing the doc, but when configuring the webextention on firefox the validation of new server with proper public cert (retreived automaticaly by the extention) give this message : 
"This public key does not match the one required by the server."

**Comment by llevet** [comment]
Seem to be the no docummented parameter in api.php : 
 $response->cmh_sha256 = 'SHA256_FINGERPRINT_OF_YOUR_SERVER_S_HTTPS_CERTIFICATE';

**Comment by Shiluba** [comment]
Hello llevet,

Indeed, you have to set the value of `$response->cmh_sha256` (in `api.php`) with the SHA256 fingerprint of your server's HTTPS certificate.

You can get this value with this command:
`openssl x509 -in your_certificate.crt -inform PEM -out /dev/stdout -outform DER | sha256sum`

We will re test all setup procedures during this week-end, complete the documentation and keep you informed.

Thanks for your interest in this project.
Let us know if you have further questions.

Regards,

CheckMyHTTPS Team

**Comment by llevet** [comment]
Your command give me the same SHA-256 result as viewing the web certificat in firefox, so it is good.
But it continu to give me "This public key does not match the one required by the server."

And also, i don't see the relation beetween my ssl certificat on my httpd server and the private/public key of the app during the validation of the new server ...

**Comment by Shiluba** [comment]
Yes, at least your SHA256 hash is correct.
Don't worry, this might be a small error in the code, I will try to reproduce your situation to check that.

To answer your question, there is actually no relation between the SSL certificate of your HTTPD server and the RSA key pair used by CheckMyHTTPS (that you must create by following the documentation).

The RSA key pair's role is for the client to make sure it contacts the good CMH server (by verifying the signature of the server with its public key) and that there is no Man-In-The-Middle attack even between the CMH client and the CMH server.

Have you carefully read the [README.md](https://github.com/checkmyhttps/checkmyhttps/blob/master/server-php/README.md) in the folder [server-php](https://github.com/checkmyhttps/checkmyhttps/tree/master/server-php) ?

**Comment by llevet** [comment]
Yes, i read the README.md file. 
But the error message is about "public key" but in fact, it seem to be the validation of the fingerprint of httpd public certificat. 
This suggests that the problem come from the couple RSA key pair, but in fact the problem seem to be a mismatch in the figerprint of the http cert...

For this case, the message  should be "The public certificate does not match the one the server should have" insteed of  "This public key does not match the one required by the server." ....

**Comment by llevet** [comment]
Ok, i found the problem.
In source client code checkmyhttps/webextension/lib/certificatesManager.js line number 88 the fingerprints is put in upper case.

So the $response->cmh_sha256 in api.php must be put in upper case .... 
It miss a strtoupper() on line 389

**Comment by llevet** [comment]
For those interested
A linux script to update automatically the fingerprint after a letsencrypt renew cert : 
[update_fingerprint.txt](https://github.com/checkmyhttps/checkmyhttps/files/13998414/update_fingerprint.txt)

**Comment by Shiluba** [comment]
Hello, you are right, the SHA256 fingerprint needs to be uppercase in `api.php`, I will add it to the documentation right now.

A client update will be deployed in the coming days (starting with Firefox) with more and better error messages.

Thank you for your feedback.

Let me know if you have any further questions related to this issue, otherwise I will close this case.

Regards,

CheckMyHTTPS Team

**Comment by Shiluba** [comment]
Firefox WebExtension 5.7.1 update is live.

Regards,

CheckMyHTTPS Team
