### ISSUE TITLE
webextension on private server doesn't work properly at browser startup 

### ISSUE THREAD

**Issue by llevet** [checkmyhttps/checkmyhttps#72]
Hi,
When you have a custom server, the webextention doesn't work (alway give a fail result) at the startup of the browser (Firefox in my case).
You must revalidate the config (by pushing save) in the extention to revert to normal.
Each time you close completly the browser, you must revalidate for proper operation.

**Comment by llevet** [comment]
Hi,

I have found the problem.

 
When the browser start,  "verifyServerAtStartup", on checkmyhttps/webextension/lib/options.js line 164, is verify the server define in "Cache of extension options" systematicaly (so server https://checkmyhttps.net/) but not our.
But during this process, on checkmyhttps/webextension/lib/options.js line 86, it set the value of CMH.options.importedPublicKey. But this value is improper set because it is not our server.
The loading of the setting store on brower arrived just after on checkmyhttps/webextension/lib/options.js line 180, but to late, because value of CMH.options.importedPublicKey is not our. 

So, verifyServerAtStartup must check the server define in the storage (if it exist), but not systematicaly the default server in "Cache of extension options"

The code must be change from starting line 163 :

`// Verify the server's signature AND if there is a passive Man In The Middle
CMH.options.verifyServerAtStartup(CMH.options.settings.checkServerUrl, CMH.options.settings.publicKey).then((response) => {
  switch(response) {
    case 1:
      break;
    case -1:
      CMH.ui.showNotification(browser.i18n.getMessage('__defaultServerUnreachable__'));
      break;
    case -2:
      CMH.ui.showNotification(browser.i18n.getMessage('__invalidPublicKey__'), { openOptionsPage: 1 });
      break;
    default:
      CMH.ui.showNotification(browser.i18n.getMessage('__serverSignatureNotVerified__'));
      break;
  }
});

// Get settings values
browser.storage.local.get(['checkOnPageLoad', 'alertOnUnicodeIDNDomainNames', 'disableNotifications', 'checkServerUrl', 'publicKey']).then((settings) => {
  const settingsItems = Object.keys(settings)

  for (let item of settingsItems) {
    CMH.options.settings[item] = settings[item]
  }
}, (error) => { console.error(error) })`


to : 


`// Get settings values
browser.storage.local.get(['checkOnPageLoad', 'alertOnUnicodeIDNDomainNames', 'disableNotifications', 'checkServerUrl', 'publicKey']).then((settings) => {
  const settingsItems = Object.keys(settings)

  for (let item of settingsItems) {
    CMH.options.settings[item] = settings[item];
	console.log(item);
	console.log(CMH.options.settings.checkServerUrl);
	console.log(settings[item]);
	console.log(CMH.options.settings.publicKey);
  }  
  // Verify the server's signature AND if there is a passive Man In The Middle
  CMH.options.verifyServerAtStartup(CMH.options.settings.checkServerUrl, CMH.options.settings.publicKey).then((response) => {
    console.log('-------');
    console.log(CMH.options.settings.checkServerUrl);
    console.log(CMH.options.settings.publicKey);  
    switch(response) {
      case 1:
	    console.log('retour verif ok');
        break;
      case -1:
        CMH.ui.showNotification(browser.i18n.getMessage('__defaultServerUnreachable__'));
        break;
      case -2:
        CMH.ui.showNotification(browser.i18n.getMessage('__invalidPublicKey__'), { openOptionsPage: 1 });
        break;
      default:
        CMH.ui.showNotification(browser.i18n.getMessage('__serverSignatureNotVerified__'));
        break;
    }
  });  
}, (error) => { console.error(error) })
`

This change is working fine for me.
I suppose the modification must be done also on Chromium.

**Comment by llevet** [comment]
Hi,

I have found the problem.

 
When the browser start,  "verifyServerAtStartup", on checkmyhttps/webextension/lib/options.js line 164, is verify the server define in "Cache of extension options" systematicaly (so server https://checkmyhttps.net/) but not our.
But during this process, on checkmyhttps/webextension/lib/options.js line 86, it set the value of CMH.options.importedPublicKey. But this value is improper set because it is not our server.
The loading of the setting store on brower arrived just after on checkmyhttps/webextension/lib/options.js line 180, but to late, because value of CMH.options.importedPublicKey is not our. 

So, "verifyServerAtStartup" must check the server define in the storage (if it exist), but not systematicaly the default server in "Cache of extension options"

New code is in attachement.
[new_code.txt](https://github.com/checkmyhttps/checkmyhttps/files/14000029/new_code.txt)

**Comment by Shiluba** [comment]
Hello, exactly, this will be implemented in the next client update.

Once again, thanks for your advice.

We will close this case when the update will be published.

Regards,

CheckMyHTTPS Team

**Comment by llevet** [comment]
Great, thanks !

**Comment by Shiluba** [comment]
Firefox WebExtension 5.7.1 update is live.

Regards,

CheckMyHTTPS Team
