### ISSUE TITLE
Behind a proxy

### ISSUE THREAD

**Issue by gronono** [checkmyhttps/checkmyhttps#9]
I wonder if this extensions can work behind an http proxy.

My computer can acces to https://checkmyhttps.net/
```
✗ curl https://checkmyhttps.net/   
<!DOCTYPE HTML>
<html>
	<head>
		<title>CheckMyHTTPS</title>
....
```
But in my browser I got the message "Serveur injoignable" (server unreachable).

Regards.

**Comment by Tom-H-** [comment]
Hello,

If I understand correctly, you are talking about an HTTPS proxy between your CheckMyHTTPS and the Internet.

In that case, you are probably intercepted by it. You can check it manually via the website https://checkmyhttps.net/info.php (at the bottom of the page).

**Comment by gronono** [comment]
Hi,

The request seems not being intercepted.

```
✗ curl -vv https://checkmyhttps.net/
* Uses proxy env variable https_proxy == 'http://localhost:3128'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3128 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to checkmyhttps.net:443
> CONNECT checkmyhttps.net:443 HTTP/1.1
> Host: checkmyhttps.net:443
> User-Agent: curl/7.61.1
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< Connection: close
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* CONNECT phase completed!
* CONNECT phase completed!
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; OU=Gandi Standard SSL; CN=checkmyhttps.net
*  start date: Oct 21 00:00:00 2016 GMT
*  expire date: Nov 30 23:59:59 2019 GMT
*  subjectAltName: host "checkmyhttps.net" matched cert's "checkmyhttps.net"
*  issuer: C=FR; ST=Paris; L=Paris; O=Gandi; CN=Gandi Standard SSL CA 2
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: checkmyhttps.net
> User-Agent: curl/7.61.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 23 Oct 2018 06:24:45 GMT
< Server: Apache
< Content-Length: 3569
< Content-Type: text/html; charset=UTF-8
< 
```

I manually check with your website and the signatures matches.

Regards

**Comment by Tom-H-** [comment]
Hello,

I have added proxy support to the Python script on the repo in commit a309211. I have tested it with a squid server and the proxy setting set on the operating system.

Can you confirm me that it works behind your proxy before I publish the new version on browser stores ?

Thanks

**Comment by gronono** [comment]
Thanks. I can't test it before a week (I'm on vacation)

**Comment by gronono** [comment]
I comment out print statements around lines 384. And I got:

```
$ ./checkmyhttps.py check https://checkmyhttps.net/
Connection error: <urlopen error Tunnel connection failed: 407 Proxy Authentication Required>
```

My configuration is quite complicated. I have local proxy provided by cntlm to provide NTLM authentication, which delegates to another proxy access to the Internet.

But my local proxy does not need authentication.

**Comment by gronono** [comment]
The three cases always return a 407 error.

I compared HTTP requests between curl and your script. I found that curl adds a "Proxy-Connection" header with the value "Keep-Alive" when it makes the CONNECT request.

I added this header in my cntlm configuration file to always add it.
And it works now :)

Thank you very much.

**Comment by gronono** [comment]
And it also work with the previous version of the script

**Comment by Tom-H-** [comment]
Yeah this is normal, the old version was not compatible with proxy.

I close this issue since it's now working.

**Comment by gronono** [comment]
Thanks again.

**Comment by checkmyhttps** [comment]
yes, by talking about it and liking it (stars) ;-)
Coming soon : android & Ios Apps (developed by Catarina).
